main:
- identifier: Global Scores
  name: Global Scores
  weight: 1
- identifier: Methodology
  name: Methodology
  weight: 2
- identifier: OHI+
  name: OHI<b style="color:#f26c25">+</b>
  weight: 3
- identifier: Resources
  name: Resources
  weight: 4
- identifier: About
  name: About
  weight: 5