dist: focal
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
  - npm i
  - hugo version
  - if [ "$TRAVIS_BRANCH" = "main" ]; then hugo --baseURL 'http://dev.oceanhealthindex.org'; fi
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.82.0
  - TEST=2

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: main