######################## Site Wide Configuration ####################
baseURL = "http://oceanhealthindex.org"
title = "Ocean Health Index"
theme = "ohi"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

#################### default parameters ################################
[params]
logo = "images/logo.png"
description = "OHI Logo"
author = "Ocean Health Index"
top_header = true

################################### English language #####################################
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "home"

################### Navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Global Scores"
url = "alien-species"
weight = 1

  [[Languages.en.menu.main]]
  parent = "Global Scores"
  name = "Scores"
  url = "alien-species"

  [[Languages.en.menu.main]]
  parent = "Global Scores"
  name = "Annual Scores and Rankings"
  url = "annual-scores-and-rankings"
  
  [[Languages.en.menu.main]]
  parent = "Global Scores"
  name = "Key Findings"
  url = "key-findings"
  
  [[Languages.en.menu.main]]
  parent = "Global Scores"
  name = "Maps"
  url = "maps"

  [[Languages.en.menu.main]]
  parent = "Global Scores"
  name = "Downloads"
  url = "downloads"

[[Languages.en.menu.main]]
name = "OHI +"
url = "ohi-plus"
weight = 1

[[Languages.en.menu.main]]
name = "METHODOLOGY"
url = "methodology"
weight = 2
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "METHODOLOGY"
  name = "Methods Overview"
  url = "methodology"
  
  [[Languages.en.menu.main]]
  parent = "METHODOLOGY"
  name = "Goal Descriptions"
  url = "goals"

  [[Languages.en.menu.main]]
  parent = "METHODOLOGY"
  name = "Pressure Descriptions"
  url = "components"

  [[Languages.en.menu.main]]
  parent = "METHODOLOGY"
  name = "Resilience Descriptions"
  url = "components"

  [[Languages.en.menu.main]]
  parent = "METHODOLOGY"
  name = "OHI Global Methods Deep Dive"
  url = "components"

[[Languages.en.menu.main]]
name = "News"
url = "news"
weight = 3

[[Languages.en.menu.main]]
weight = 4
name = "About"
url = "about"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "About"
  name = "Team"
  url = "about"

  [[Languages.en.menu.main]]
  parent = "About"
  name = "Contributors"
  url = "contributors"

  [[Languages.en.menu.main]]
  parent = "About"
  name = "Sustaining Partners"
  url = "sustaining-partners"

  [[Languages.en.menu.main]]
  parent = "About"
  name = "FAQ"
  url = "faq"

  [[Languages.en.menu.main]]
  parent = "About"
  name = "Glossary"
  url = "glossary"


  [[Languages.en.menu.main]]
  parent = "About"
  name = "Contact"
  url = "contact"

# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"
