name = "Ocean Health Index"
license = "CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "The main theme for the Ocean Health Index project"
homepage = "https://oceanhealthindex.org"
tags = ["ocean health"]
