---
title: "Create a markdown page for each region in the OHI website"
author: "Robyn Thiessen-Bock"
date: "2021-07-07"
---

This R code reads in the `scores.csv` file and creates a markdown page for each country/region in the scores file.

```{r}
library(here)
library(dplyr)
library(magrittr)
library(stringi)
```

Below are all of the configurable variables that can be changed depending on updates to the scores.CSV file and to the template that is used to create the Hugo font-matter

```{r}
# Path to the scores.csv file
scores_path <- here("content", "data", "scores.csv")
# Path to where the region markdown pages should be created. This directory must already exist.
output_dir <- here("content", "regions")
# In the scores.csv file, the name for the column that contains the region names
name_col <- "region_name"
# In the scores.csv file, the name for the column that contains the region Ids
id_col <- "region_id"
# In the scores.csv file, the name for the column that contains 
value_col <- "value"
# In the scores.csv file, the name for the column that contains the types of dimensions (score, future, etc.)
dimension_col <- "dimension"
# In the scores.csv file, the name for the column that has codes for each goal (e.g. AO, BD, etc.)
goal_col <- "goal"
# In the scores.csv file, the name for the column that contains the years
year_col <- "scenario"
# In the scores.csv file, the dimension used to identify OHI scores
score_rows <- "score"
# In the scores.csv file, the identifier in the column of goal identifiers that indicates the score/value is the overall average of all goals
average_goal <- "Index"
# The region_name used for the global average scores
global_avg_name <- "Global average"
# In the scores.csv file, the names of any regions that we should not create pages for
exclude_regions <- c(global_avg_name, "Antarctica")
# The template to use when creating front-matter for the region markdown file page. $id and $name are replaced with the region ID and name.
template <- "---
regionId: $id
title: $name
rank: $rank
meanScore: $meanScore
globalMeanScore: $globalMeanScore
numRegions: $numRegions
layout: region_score
---"
```

The next section organizes the data

```{r}
# Get the data from the scores csv file. Get just the unique region names and IDs.
all_data <- read.csv(scores_path)

# Get the number of regions
num_regions <- scores_data %>% 
	filter(!(!!as.symbol(name_col) %in% exclude_regions)) %>% 
	.[,name_col] %>%
	unique() %>% 
	length()

# Find the most recent year
max_year <- all_data[,year_col] %>% max()

# Exclude any data that we don't need to create a site page for
scores_data <- all_data %>% 
	filter(!!as.symbol(dimension_col) == "score") %>% 
	filter(!!as.symbol(year_col) == max_year) %>% 
	filter(!!as.symbol(goal_col) == average_goal)

# Exclude any regions that we don't want to make pages for
page_data <- scores_data %>% 
	filter(!(!!as.symbol(name_col) %in% exclude_regions)) %>% 
	arrange(desc(!!as.symbol(value_col)))

# Get the global average score
global_avg <- scores_data %>% 
	filter(!!as.symbol(name_col) == global_avg_name ) %>% 
	.[, value_col]

```

Create a template for each page

```{r}
# Update the template with the global mean score and the number of regions. This only needs to be done once since it is the same value for all regions.

template <- gsub("\\$globalMeanScore", global_avg, template)
template <- gsub("\\$numRegions", num_regions, template)
	
# Make a markdown file for each region
for (row in 1:nrow(page_data)) {
	
	name <- page_data[row, name_col]
	id  <- page_data[row, id_col]
	score <- page_data[row, value_col]
	rank <- row # because the data is sorted
	
	templateCopy <- template
	templateCopy <- gsub("\\$id", id, templateCopy)
	templateCopy <- gsub("\\$name", name, templateCopy)
	templateCopy <- gsub("\\$rank", rank, templateCopy)
	templateCopy <- gsub("\\$meanScore", score, templateCopy)
	
	# Make the markdown file name from the region name
	fileName <- name %>%
		tolower() %>% # make lower case
		gsub("\\s*\\([^\\)]+\\)","", .) %>% # remove text between parentheses at end of name
		stri_trans_general("Latin-ASCII") %>% # convert characters with accents to non-accented character
		gsub("\\s","-", .) %>%  # convert spaces to dashes
		paste0(., ".md") #Add the markdown extension
	
	fileConn<-file(here(output_dir, fileName))
	writeLines(templateCopy, fileConn)
	close(fileConn)
}
```