name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          npm install
          hugo --baseURL="https://ohi-science.org/OHI-website/"

      # Copy the source to the nceas server
      - name: Copy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          local: "public/."
          remote: ${{ secrets.DEPLOY_PATH }}
          rm: true
