name: Deploy Preview

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: |
          npm install
          hugo --baseURL="https://preview.oceanhealthindex.org/"
      # Copy the source to the nceas server
      - name: Copy
        uses: dataoneorg/rsync-deploy@latest
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "public/"
          target: ${{ secrets.DEPLOY_PATH_DEV }}
